using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using ComparePOC.Model;

namespace ComparePOC.Comparer;

public class PersonEqualityComparer : EqualityComparer<Person>
{
    private readonly ILogger<PersonEqualityComparer> _logger;

    public PersonEqualityComparer(ILogger<PersonEqualityComparer> logger)
    {
        _logger = logger;
    }

    public override bool Equals(Person? x, Person? y)
    {
        if (x is null || y is null)
            return false;

        var hashPersonX = GetHashCode(x);
        var hashPersonY = GetHashCode(y);

        _logger.LogInformation($"Hashcode generated by person x: {hashPersonX}");
        _logger.LogInformation($"Hashcode generated by person y: {hashPersonY}");
        _logger.LogInformation($"Hashcode comparison between person x and person y result: {hashPersonX == hashPersonY}");

        return hashPersonX == hashPersonY;
    }

    public override int GetHashCode([DisallowNull] Person obj)
    {
        return (JsonSerializer.Serialize(obj)).GetHashCode();
    }
}